# Generated by Django 5.2.8 on 2025-11-18 22:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0002_test_is_restricted_assignment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('stream', models.CharField(choices=[('bokmaal', 'Bokmål'), ('nynorsk', 'Nynorsk'), ('english', 'English')], default='bokmaal', max_length=20)),
                ('level', models.CharField(choices=[('A1', 'A1 - Beginner'), ('A2', 'A2 - Elementary'), ('B1', 'B1 - Intermediate'), ('B2', 'B2 - Upper-intermediate')], default='A1', max_length=2)),
                ('kind', models.CharField(choices=[('quiz', 'Quiz'), ('dictation', 'Dictation'), ('flashcard', 'Flashcard')], default='quiz', max_length=20)),
                ('prompt', models.TextField(blank=True)),
                ('data', models.JSONField(blank=True, default=dict)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('estimated_minutes', models.PositiveIntegerField(default=5)),
                ('assigned_to_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['level', 'title'],
            },
        ),
        migrations.CreateModel(
            name='Expression',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phrase', models.CharField(max_length=255)),
                ('meaning', models.TextField()),
                ('example', models.TextField(blank=True)),
                ('stream', models.CharField(choices=[('bokmaal', 'Bokmål'), ('nynorsk', 'Nynorsk'), ('english', 'English')], default='bokmaal', max_length=20)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['phrase'],
            },
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('stream', models.CharField(choices=[('bokmaal', 'Bokmål'), ('nynorsk', 'Nynorsk'), ('english', 'English')], default='bokmaal', max_length=20)),
                ('level', models.CharField(choices=[('A1', 'A1 - Beginner'), ('A2', 'A2 - Elementary'), ('B1', 'B1 - Intermediate'), ('B2', 'B2 - Upper-intermediate')], default='A1', max_length=2)),
                ('material_type', models.CharField(choices=[('text', 'Text'), ('video', 'Video'), ('audio', 'Audio')], default='text', max_length=10)),
                ('body', models.TextField(blank=True)),
                ('url', models.URLField(blank=True)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('is_published', models.BooleanField(default=True)),
                ('assigned_to_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['level', 'title'],
            },
        ),
        migrations.CreateModel(
            name='VerbEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verb', models.CharField(max_length=120)),
                ('stream', models.CharField(choices=[('bokmaal', 'Bokmål'), ('nynorsk', 'Nynorsk'), ('english', 'English')], default='bokmaal', max_length=20)),
                ('infinitive', models.CharField(max_length=120)),
                ('present', models.CharField(max_length=120)),
                ('past', models.CharField(max_length=120)),
                ('perfect', models.CharField(max_length=120)),
                ('examples', models.TextField(blank=True)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['verb'],
            },
        ),
        migrations.AddField(
            model_name='test',
            name='stream',
            field=models.CharField(choices=[('bokmaal', 'Bokmål'), ('nynorsk', 'Nynorsk'), ('english', 'English')], default='bokmaal', help_text='Content stream: Bokmål, Nynorsk or English', max_length=20),
        ),
        migrations.AlterField(
            model_name='submission',
            name='locale',
            field=models.CharField(choices=[('en', 'English'), ('nb', 'Norsk'), ('ru', 'Русский')], default='en', max_length=5),
        ),
        migrations.AlterField(
            model_name='test',
            name='level',
            field=models.CharField(choices=[('A1', 'A1 - Beginner'), ('A2', 'A2 - Elementary'), ('B1', 'B1 - Intermediate'), ('B2', 'B2 - Upper-intermediate')], max_length=2),
        ),
        migrations.CreateModel(
            name='GlossaryTerm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term', models.CharField(max_length=255)),
                ('translation', models.CharField(blank=True, max_length=255)),
                ('explanation', models.TextField(blank=True)),
                ('stream', models.CharField(choices=[('bokmaal', 'Bokmål'), ('nynorsk', 'Nynorsk'), ('english', 'English')], default='bokmaal', max_length=20)),
                ('level', models.CharField(choices=[('A1', 'A1 - Beginner'), ('A2', 'A2 - Elementary'), ('B1', 'B1 - Intermediate'), ('B2', 'B2 - Upper-intermediate')], default='A1', max_length=2)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['term'],
                'unique_together': {('term', 'stream', 'level')},
            },
        ),
        migrations.CreateModel(
            name='Homework',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('stream', models.CharField(choices=[('bokmaal', 'Bokmål'), ('nynorsk', 'Nynorsk'), ('english', 'English')], default='bokmaal', max_length=20)),
                ('level', models.CharField(choices=[('A1', 'A1 - Beginner'), ('A2', 'A2 - Elementary'), ('B1', 'B1 - Intermediate'), ('B2', 'B2 - Upper-intermediate')], default='A1', max_length=2)),
                ('due_date', models.DateTimeField(blank=True, null=True)),
                ('instructions', models.TextField()),
                ('attachments', models.JSONField(blank=True, default=list)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('closed', 'Closed')], default='published', max_length=20)),
                ('assigned_to_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('student_submission', models.TextField(blank=True)),
                ('feedback', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='homeworks_given', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-due_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StudentProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('stream', models.CharField(choices=[('bokmaal', 'Bokmål'), ('nynorsk', 'Nynorsk'), ('english', 'English')], default='bokmaal', max_length=20)),
                ('level', models.CharField(choices=[('A1', 'A1 - Beginner'), ('A2', 'A2 - Elementary'), ('B1', 'B1 - Intermediate'), ('B2', 'B2 - Upper-intermediate')], default='A1', max_length=2)),
                ('allow_stream_change', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students_assigned', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='student_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['email'],
            },
        ),
    ]
