# Generated by Django 5.2.8 on 2025-11-18 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0003_exercise_expression_material_verbentry_test_stream_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='stream',
            field=models.CharField(choices=[('bokmaal', 'Bokmal'), ('nynorsk', 'Nynorsk'), ('english', 'English')], default='bokmaal', max_length=20),
        ),
        migrations.AlterField(
            model_name='expression',
            name='stream',
            field=models.CharField(choices=[('bokmaal', 'Bokmal'), ('nynorsk', 'Nynorsk'), ('english', 'English')], default='bokmaal', max_length=20),
        ),
        migrations.AlterField(
            model_name='glossaryterm',
            name='stream',
            field=models.CharField(choices=[('bokmaal', 'Bokmal'), ('nynorsk', 'Nynorsk'), ('english', 'English')], default='bokmaal', max_length=20),
        ),
        migrations.AlterField(
            model_name='homework',
            name='stream',
            field=models.CharField(choices=[('bokmaal', 'Bokmal'), ('nynorsk', 'Nynorsk'), ('english', 'English')], default='bokmaal', max_length=20),
        ),
        migrations.AlterField(
            model_name='material',
            name='stream',
            field=models.CharField(choices=[('bokmaal', 'Bokmal'), ('nynorsk', 'Nynorsk'), ('english', 'English')], default='bokmaal', max_length=20),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='stream',
            field=models.CharField(choices=[('bokmaal', 'Bokmal'), ('nynorsk', 'Nynorsk'), ('english', 'English')], default='bokmaal', max_length=20),
        ),
        migrations.AlterField(
            model_name='submission',
            name='locale',
            field=models.CharField(choices=[('en', 'English'), ('nb', 'Norsk'), ('ru', 'Russian')], default='en', max_length=5),
        ),
        migrations.AlterField(
            model_name='test',
            name='stream',
            field=models.CharField(choices=[('bokmaal', 'Bokmal'), ('nynorsk', 'Nynorsk'), ('english', 'English')], default='bokmaal', help_text='Content stream: Bokmal, Nynorsk or English', max_length=20),
        ),
        migrations.AlterField(
            model_name='verbentry',
            name='stream',
            field=models.CharField(choices=[('bokmaal', 'Bokmal'), ('nynorsk', 'Nynorsk'), ('english', 'English')], default='bokmaal', max_length=20),
        ),
    ]
