# Generated by Django 5.2.8 on 2025-11-19 18:01

from django.db import migrations, models


def split_examples(apps, schema_editor):
    VerbEntry = apps.get_model("exams", "VerbEntry")
    for entry in VerbEntry.objects.all():
        raw = (entry.examples or "").splitlines() if hasattr(entry, "examples") else []
        lines = [line.strip() for line in raw if line.strip()]
        buckets = {
            "examples_infinitive": "\n".join(lines[0:1]),
            "examples_present": "\n".join(lines[1:2]),
            "examples_past": "\n".join(lines[2:3]),
            "examples_perfect": "\n".join(lines[3:4]),
        }
        for field, value in buckets.items():
            setattr(entry, field, value)
        entry.save(update_fields=list(buckets.keys()))


def merge_examples(apps, schema_editor):
    VerbEntry = apps.get_model("exams", "VerbEntry")
    for entry in VerbEntry.objects.all():
        lines = [
            entry.examples_infinitive or "",
            entry.examples_present or "",
            entry.examples_past or "",
            entry.examples_perfect or "",
        ]
        lines = [line for line in lines if line]
        setattr(entry, "examples", "\n".join(lines))
        entry.save(update_fields=["examples"])


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0004_alter_exercise_stream_alter_expression_stream_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name="verbentry",
            name="examples_infinitive",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="verbentry",
            name="examples_present",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="verbentry",
            name="examples_past",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="verbentry",
            name="examples_perfect",
            field=models.TextField(blank=True),
        ),
        migrations.RunPython(split_examples, reverse_code=merge_examples),
        migrations.RemoveField(
            model_name="verbentry",
            name="examples",
        ),
    ]
