from django.db import migrations


def seed_batch2(apps, schema_editor):
    GlossaryTerm = apps.get_model("exams", "GlossaryTerm")
    items = [
        # coffee
        {
            "term": "kaffe",
            "translation": "coffee",
            "translation_en": "coffee",
            "translation_ru": "кофе",
            "translation_nb": "kaffe",
            "explanation": "Jeg drikker kaffe med venner. (Bokmål)",
            "stream": "bokmaal",
            "level": "A1",
            "tags": ["drikk", "hverdag"],
        },
        {
            "term": "kaffi",
            "translation": "coffee",
            "translation_en": "coffee",
            "translation_ru": "кофе",
            "translation_nb": "kaffe",
            "explanation": "Eg lagar kaffi kvar morgon. (Nynorsk)",
            "stream": "nynorsk",
            "level": "A1",
            "tags": ["drikk", "kvardag"],
        },
        {
            "term": "coffee",
            "translation": "кофе",
            "translation_en": "coffee",
            "translation_ru": "кофе",
            "translation_nb": "kaffe",
            "explanation": "We drink coffee before class. (English)",
            "stream": "english",
            "level": "A1",
            "tags": ["drink", "daily"],
        },
        # library
        {
            "term": "bibliotek",
            "translation": "library",
            "translation_en": "library",
            "translation_ru": "библиотека",
            "translation_nb": "bibliotek",
            "explanation": "Biblioteket er stille og lyst. (Bokmål)",
            "stream": "bokmaal",
            "level": "A1",
            "tags": ["sted", "studie"],
        },
        {
            "term": "bibliotek",
            "translation": "library",
            "translation_en": "library",
            "translation_ru": "библиотека",
            "translation_nb": "bibliotek",
            "explanation": "Eg les ei bok på biblioteket. (Nynorsk)",
            "stream": "nynorsk",
            "level": "A1",
            "tags": ["stad", "studie"],
        },
        {
            "term": "library",
            "translation": "библиотека",
            "translation_en": "library",
            "translation_ru": "библиотека",
            "translation_nb": "bibliotek",
            "explanation": "The library opens at eight. (English)",
            "stream": "english",
            "level": "A1",
            "tags": ["place", "study"],
        },
        # student
        {
            "term": "student",
            "translation": "student",
            "translation_en": "student",
            "translation_ru": "студент",
            "translation_nb": "student",
            "explanation": "Hun er student ved universitetet. (Bokmål)",
            "stream": "bokmaal",
            "level": "A1",
            "tags": ["skole"],
        },
        {
            "term": "student",
            "translation": "student",
            "translation_en": "student",
            "translation_ru": "студент",
            "translation_nb": "student",
            "explanation": "Han er student og bur i Bergen. (Nynorsk)",
            "stream": "nynorsk",
            "level": "A1",
            "tags": ["skule"],
        },
        {
            "term": "student",
            "translation": "студент",
            "translation_en": "student",
            "translation_ru": "студент",
            "translation_nb": "student",
            "explanation": "The student studies Norwegian every day. (English)",
            "stream": "english",
            "level": "A1",
            "tags": ["school"],
        },
        # airplane
        {
            "term": "fly",
            "translation": "airplane",
            "translation_en": "airplane",
            "translation_ru": "самолёт",
            "translation_nb": "fly",
            "explanation": "Flyet lander om ti minutter. (Bokmål)",
            "stream": "bokmaal",
            "level": "A1",
            "tags": ["reise"],
        },
        {
            "term": "fly",
            "translation": "airplane",
            "translation_en": "airplane",
            "translation_ru": "самолёт",
            "translation_nb": "fly",
            "explanation": "Flyet kjem snart til Oslo. (Nynorsk)",
            "stream": "nynorsk",
            "level": "A1",
            "tags": ["reise"],
        },
        {
            "term": "airplane",
            "translation": "самолёт",
            "translation_en": "airplane",
            "translation_ru": "самолёт",
            "translation_nb": "fly",
            "explanation": "The airplane is ready for boarding. (English)",
            "stream": "english",
            "level": "A1",
            "tags": ["travel"],
        },
        # winter
        {
            "term": "vinter",
            "translation": "winter",
            "translation_en": "winter",
            "translation_ru": "зима",
            "translation_nb": "vinter",
            "explanation": "Vinteren er kald, men fin. (Bokmål)",
            "stream": "bokmaal",
            "level": "A1",
            "tags": ["årstid"],
        },
        {
            "term": "vinter",
            "translation": "winter",
            "translation_en": "winter",
            "translation_ru": "зима",
            "translation_nb": "vinter",
            "explanation": "Om vinteren går vi på ski. (Nynorsk)",
            "stream": "nynorsk",
            "level": "A1",
            "tags": ["årstid"],
        },
        {
            "term": "winter",
            "translation": "зима",
            "translation_en": "winter",
            "translation_ru": "зима",
            "translation_nb": "vinter",
            "explanation": "Winter days are short in Norway. (English)",
            "stream": "english",
            "level": "A1",
            "tags": ["season"],
        },
        # friendship
        {
            "term": "vennskap",
            "translation": "friendship",
            "translation_en": "friendship",
            "translation_ru": "дружба",
            "translation_nb": "vennskap",
            "explanation": "Vennskap bygges med tid. (Bokmål)",
            "stream": "bokmaal",
            "level": "A2",
            "tags": ["følelser"],
        },
        {
            "term": "vennskap",
            "translation": "friendship",
            "translation_en": "friendship",
            "translation_ru": "дружба",
            "translation_nb": "vennskap",
            "explanation": "Ekte vennskap varer lenge. (Nynorsk)",
            "stream": "nynorsk",
            "level": "A2",
            "tags": ["kjensler"],
        },
        {
            "term": "friendship",
            "translation": "дружба",
            "translation_en": "friendship",
            "translation_ru": "дружба",
            "translation_nb": "vennskap",
            "explanation": "Friendship grows when we share time. (English)",
            "stream": "english",
            "level": "A2",
            "tags": ["feelings"],
        },
        # computer
        {
            "term": "data",
            "translation": "computer",
            "translation_en": "computer",
            "translation_ru": "компьютер",
            "translation_nb": "datamaskin",
            "explanation": "Jeg bruker data på jobb. (Bokmål)",
            "stream": "bokmaal",
            "level": "A2",
            "tags": ["teknologi"],
        },
        {
            "term": "data",
            "translation": "computer",
            "translation_en": "computer",
            "translation_ru": "компьютер",
            "translation_nb": "datamaskin",
            "explanation": "Eg skriv på data kvar dag. (Nynorsk)",
            "stream": "nynorsk",
            "level": "A2",
            "tags": ["teknologi"],
        },
        {
            "term": "computer",
            "translation": "компьютер",
            "translation_en": "computer",
            "translation_ru": "компьютер",
            "translation_nb": "datamaskin",
            "explanation": "A computer helps me work faster. (English)",
            "stream": "english",
            "level": "A2",
            "tags": ["tech"],
        },
        # music
        {
            "term": "musikk",
            "translation": "music",
            "translation_en": "music",
            "translation_ru": "музыка",
            "translation_nb": "musikk",
            "explanation": "Musikk gir energi på morgenen. (Bokmål)",
            "stream": "bokmaal",
            "level": "A2",
            "tags": ["kultur"],
        },
        {
            "term": "musikk",
            "translation": "music",
            "translation_en": "music",
            "translation_ru": "музыка",
            "translation_nb": "musikk",
            "explanation": "Eg høyrer på musikk når eg jobbar. (Nynorsk)",
            "stream": "nynorsk",
            "level": "A2",
            "tags": ["kultur"],
        },
        {
            "term": "music",
            "translation": "музыка",
            "translation_en": "music",
            "translation_ru": "музыка",
            "translation_nb": "musikk",
            "explanation": "Music helps me concentrate. (English)",
            "stream": "english",
            "level": "A2",
            "tags": ["culture"],
        },
        # city
        {
            "term": "by",
            "translation": "city",
            "translation_en": "city",
            "translation_ru": "город",
            "translation_nb": "by",
            "explanation": "Byen har mange parker. (Bokmål)",
            "stream": "bokmaal",
            "level": "A2",
            "tags": ["sted"],
        },
        {
            "term": "by",
            "translation": "city",
            "translation_en": "city",
            "translation_ru": "город",
            "translation_nb": "by",
            "explanation": "Eg bur i ein liten by ved fjorden. (Nynorsk)",
            "stream": "nynorsk",
            "level": "A2",
            "tags": ["stad"],
        },
        {
            "term": "city",
            "translation": "город",
            "translation_en": "city",
            "translation_ru": "город",
            "translation_nb": "by",
            "explanation": "The city is full of new cafes. (English)",
            "stream": "english",
            "level": "A2",
            "tags": ["place"],
        },
        # pizza
        {
            "term": "pizza",
            "translation": "pizza",
            "translation_en": "pizza",
            "translation_ru": "пицца",
            "translation_nb": "pizza",
            "explanation": "Vi bestiller pizza til kvelden. (Bokmål)",
            "stream": "bokmaal",
            "level": "A1",
            "tags": ["mat"],
        },
        {
            "term": "pizza",
            "translation": "pizza",
            "translation_en": "pizza",
            "translation_ru": "пицца",
            "translation_nb": "pizza",
            "explanation": "Eg lagar pizza heime. (Nynorsk)",
            "stream": "nynorsk",
            "level": "A1",
            "tags": ["mat"],
        },
        {
            "term": "pizza",
            "translation": "пицца",
            "translation_en": "pizza",
            "translation_ru": "пицца",
            "translation_nb": "pizza",
            "explanation": "We share a pizza with friends. (English)",
            "stream": "english",
            "level": "A1",
            "tags": ["food"],
        },
    ]
    for item in items:
        GlossaryTerm.objects.update_or_create(
            term=item["term"],
            stream=item["stream"],
            level=item["level"],
            defaults=item,
        )


def unseed_batch2(apps, schema_editor):
    GlossaryTerm = apps.get_model("exams", "GlossaryTerm")
    terms = [
        "kaffe",
        "kaffi",
        "coffee",
        "bibliotek",
        "library",
        "student",
        "fly",
        "airplane",
        "vinter",
        "winter",
        "vennskap",
        "friendship",
        "data",
        "computer",
        "musikk",
        "music",
        "by",
        "city",
        "pizza",
    ]
    GlossaryTerm.objects.filter(term__in=terms).delete()


class Migration(migrations.Migration):
    dependencies = [
        ("exams", "0013_glossary_multilang"),
    ]

    operations = [
        migrations.RunPython(seed_batch2, reverse_code=unseed_batch2),
    ]
