from django.db import migrations


def reset_glossary(apps, schema_editor):
    GlossaryTerm = apps.get_model("exams", "GlossaryTerm")

    # Удаляем все существующие записи глоссария
    GlossaryTerm.objects.all().delete()

    items = [
        # house
        {
            "term": "hus",
            "translation": "house",
            "translation_en": "house",
            "translation_ru": "дом",
            "translation_nb": "hus",
            "explanation": "Huset er lite, men hyggelig. (Bokmål)",
            "stream": "bokmaal",
            "level": "A1",
            "tags": ["hjem", "sted"],
        },
        {
            "term": "hus",
            "translation": "house",
            "translation_en": "house",
            "translation_ru": "дом",
            "translation_nb": "hus",
            "explanation": "Huset står på ei lita gate. (Nynorsk)",
            "stream": "nynorsk",
            "level": "A1",
            "tags": ["heim", "stad"],
        },
        {
            "term": "house",
            "translation": "дом",
            "translation_en": "house",
            "translation_ru": "дом",
            "translation_nb": "hus",
            "explanation": "The house is near the city center. (English)",
            "stream": "english",
            "level": "A1",
            "tags": ["home", "place"],
        },
        # book
        {
            "term": "bok",
            "translation": "book",
            "translation_en": "book",
            "translation_ru": "книга",
            "translation_nb": "bok",
            "explanation": "Jeg leser ei bok kvar kveld. (Bokmål)",
            "stream": "bokmaal",
            "level": "A1",
            "tags": ["studie", "lesing"],
        },
        {
            "term": "bok",
            "translation": "book",
            "translation_en": "book",
            "translation_ru": "книга",
            "translation_nb": "bok",
            "explanation": "Eg låner ei bok på biblioteket. (Nynorsk)",
            "stream": "nynorsk",
            "level": "A1",
            "tags": ["studie", "lesing"],
        },
        {
            "term": "book",
            "translation": "книга",
            "translation_en": "book",
            "translation_ru": "книга",
            "translation_nb": "bok",
            "explanation": "This book is easy to read. (English)",
            "stream": "english",
            "level": "A1",
            "tags": ["study", "reading"],
        },
        # friend
        {
            "term": "venn",
            "translation": "friend",
            "translation_en": "friend",
            "translation_ru": "друг",
            "translation_nb": "venn",
            "explanation": "Han er ein god venn. (Bokmål)",
            "stream": "bokmaal",
            "level": "A1",
            "tags": ["følelser"],
        },
        {
            "term": "venn",
            "translation": "friend",
            "translation_en": "friend",
            "translation_ru": "друг",
            "translation_nb": "venn",
            "explanation": "Eg møter ein venn på kafé. (Nynorsk)",
            "stream": "nynorsk",
            "level": "A1",
            "tags": ["kjensler"],
        },
        {
            "term": "friend",
            "translation": "друг",
            "translation_en": "friend",
            "translation_ru": "друг",
            "translation_nb": "venn",
            "explanation": "A friend helps me with Norwegian. (English)",
            "stream": "english",
            "level": "A1",
            "tags": ["feelings"],
        },
        # teacher
        {
            "term": "lærer",
            "translation": "teacher",
            "translation_en": "teacher",
            "translation_ru": "учитель",
            "translation_nb": "lærer",
            "explanation": "Læreren forklarer grammatikk. (Bokmål)",
            "stream": "bokmaal",
            "level": "A1",
            "tags": ["skole"],
        },
        {
            "term": "lærar",
            "translation": "teacher",
            "translation_en": "teacher",
            "translation_ru": "учитель",
            "translation_nb": "lærer",
            "explanation": "Læraren hjelper oss med oppgåvene. (Nynorsk)",
            "stream": "nynorsk",
            "level": "A1",
            "tags": ["skule"],
        },
        {
            "term": "teacher",
            "translation": "учитель",
            "translation_en": "teacher",
            "translation_ru": "учитель",
            "translation_nb": "lærer",
            "explanation": "The teacher speaks both English and Norwegian. (English)",
            "stream": "english",
            "level": "A1",
            "tags": ["school"],
        },
        # language
        {
            "term": "språk",
            "translation": "language",
            "translation_en": "language",
            "translation_ru": "язык",
            "translation_nb": "språk",
            "explanation": "Norsk er eit fint språk. (Bokmål)",
            "stream": "bokmaal",
            "level": "A1",
            "tags": ["studie"],
        },
        {
            "term": "språk",
            "translation": "language",
            "translation_en": "language",
            "translation_ru": "язык",
            "translation_nb": "språk",
            "explanation": "Russisk er også eit spennande språk. (Nynorsk)",
            "stream": "nynorsk",
            "level": "A1",
            "tags": ["studie"],
        },
        {
            "term": "language",
            "translation": "язык",
            "translation_en": "language",
            "translation_ru": "язык",
            "translation_nb": "språk",
            "explanation": "Norwegian is a new language for me. (English)",
            "stream": "english",
            "level": "A1",
            "tags": ["study"],
        },
        # food
        {
            "term": "mat",
            "translation": "food",
            "translation_en": "food",
            "translation_ru": "еда",
            "translation_nb": "mat",
            "explanation": "Vi lagar enkel mat heime. (Bokmål)",
            "stream": "bokmaal",
            "level": "A1",
            "tags": ["mat"],
        },
        {
            "term": "mat",
            "translation": "food",
            "translation_en": "food",
            "translation_ru": "еда",
            "translation_nb": "mat",
            "explanation": "Eg kjøper mat på butikken. (Nynorsk)",
            "stream": "nynorsk",
            "level": "A1",
            "tags": ["mat"],
        },
        {
            "term": "food",
            "translation": "еда",
            "translation_en": "food",
            "translation_ru": "еда",
            "translation_nb": "mat",
            "explanation": "Norwegian food is different but tasty. (English)",
            "stream": "english",
            "level": "A1",
            "tags": ["food"],
        },
        # city
        {
            "term": "by",
            "translation": "city",
            "translation_en": "city",
            "translation_ru": "город",
            "translation_nb": "by",
            "explanation": "Byen er liten, men fin. (Bokmål)",
            "stream": "bokmaal",
            "level": "A1",
            "tags": ["sted"],
        },
        {
            "term": "by",
            "translation": "city",
            "translation_en": "city",
            "translation_ru": "город",
            "translation_nb": "by",
            "explanation": "Eg bur i ein roleg by. (Nynorsk)",
            "stream": "nynorsk",
            "level": "A1",
            "tags": ["stad"],
        },
        {
            "term": "city",
            "translation": "город",
            "translation_en": "city",
            "translation_ru": "город",
            "translation_nb": "by",
            "explanation": "The city has many parks and cafes. (English)",
            "stream": "english",
            "level": "A1",
            "tags": ["place"],
        },
        # work / job
        {
            "term": "jobb",
            "translation": "job",
            "translation_en": "job",
            "translation_ru": "работа",
            "translation_nb": "jobb",
            "explanation": "Eg har jobb på kontor. (Bokmål)",
            "stream": "bokmaal",
            "level": "A1",
            "tags": ["arbeid"],
        },
        {
            "term": "jobb",
            "translation": "job",
            "translation_en": "job",
            "translation_ru": "работа",
            "translation_nb": "jobb",
            "explanation": "Ho finn ny jobb i byen. (Nynorsk)",
            "stream": "nynorsk",
            "level": "A1",
            "tags": ["arbeid"],
        },
        {
            "term": "job",
            "translation": "работа",
            "translation_en": "job",
            "translation_ru": "работа",
            "translation_nb": "jobb",
            "explanation": "I have a part-time job in a shop. (English)",
            "stream": "english",
            "level": "A1",
            "tags": ["work"],
        },
        # school
        {
            "term": "skole",
            "translation": "school",
            "translation_en": "school",
            "translation_ru": "школа",
            "translation_nb": "skole",
            "explanation": "Barna går på skole kvar dag. (Bokmål)",
            "stream": "bokmaal",
            "level": "A1",
            "tags": ["skole"],
        },
        {
            "term": "skule",
            "translation": "school",
            "translation_en": "school",
            "translation_ru": "школа",
            "translation_nb": "skole",
            "explanation": "Skulen ligg nær huset vårt. (Nynorsk)",
            "stream": "nynorsk",
            "level": "A1",
            "tags": ["skule"],
        },
        {
            "term": "school",
            "translation": "школа",
            "translation_en": "school",
            "translation_ru": "школа",
            "translation_nb": "skole",
            "explanation": "The school is next to the park. (English)",
            "stream": "english",
            "level": "A1",
            "tags": ["school"],
        },
        # train
        {
            "term": "tog",
            "translation": "train",
            "translation_en": "train",
            "translation_ru": "поезд",
            "translation_nb": "tog",
            "explanation": "Toget kjem klokka åtte. (Bokmål)",
            "stream": "bokmaal",
            "level": "A1",
            "tags": ["reise"],
        },
        {
            "term": "tog",
            "translation": "train",
            "translation_en": "train",
            "translation_ru": "поезд",
            "translation_nb": "tog",
            "explanation": "Vi tek tog til byen. (Nynorsk)",
            "stream": "nynorsk",
            "level": "A1",
            "tags": ["reise"],
        },
        {
            "term": "train",
            "translation": "поезд",
            "translation_en": "train",
            "translation_ru": "поезд",
            "translation_nb": "tog",
            "explanation": "The train is often on time in Norway. (English)",
            "stream": "english",
            "level": "A1",
            "tags": ["travel"],
        },
    ]

    for item in items:
        GlossaryTerm.objects.update_or_create(
            term=item["term"],
            stream=item["stream"],
            level=item["level"],
            defaults=item,
        )


def unreset_glossary(apps, schema_editor):
    GlossaryTerm = apps.get_model("exams", "GlossaryTerm")
    terms = [
        "hus",
        "house",
        "bok",
        "book",
        "venn",
        "friend",
        "lærer",
        "lærar",
        "teacher",
        "språk",
        "language",
        "mat",
        "food",
        "by",
        "city",
        "jobb",
        "job",
        "skole",
        "skule",
        "school",
        "tog",
        "train",
    ]
    GlossaryTerm.objects.filter(term__in=terms).delete()


class Migration(migrations.Migration):
    dependencies = [
        ("exams", "0014_seed_glossary_batch2"),
    ]

    operations = [
        migrations.RunPython(reset_glossary, reverse_code=unreset_glossary),
    ]
