from django.db import migrations


def reset_glossary_batch2(apps, schema_editor):
    GlossaryTerm = apps.get_model("exams", "GlossaryTerm")

    # Полностью очищаем словарь перед новой выборкой
    GlossaryTerm.objects.all().delete()

    items = [
        # cup
        {
            "term": "kopp",
            "translation": "cup",
            "translation_en": "cup",
            "translation_ru": "чашка",
            "translation_nb": "kopp",
            "explanation": "Eg drikk te frå ein kopp. (Bokmål)",
            "stream": "bokmaal",
            "level": "A1",
            "tags": ["kjøkken", "drikk"],
        },
        {
            "term": "kopp",
            "translation": "cup",
            "translation_en": "cup",
            "translation_ru": "чашка",
            "translation_nb": "kopp",
            "explanation": "Eg får ein varm kopp te. (Nynorsk)",
            "stream": "nynorsk",
            "level": "A1",
            "tags": ["kjøkken", "drikk"],
        },
        {
            "term": "cup",
            "translation": "чашка",
            "translation_en": "cup",
            "translation_ru": "чашка",
            "translation_nb": "kopp",
            "explanation": "I drink tea from a cup. (English)",
            "stream": "english",
            "level": "A1",
            "tags": ["kitchen", "drink"],
        },
        # water
        {
            "term": "vann",
            "translation": "water",
            "translation_en": "water",
            "translation_ru": "вода",
            "translation_nb": "vann",
            "explanation": "Eg drikk mykje vatn kvar dag. (Bokmål)",
            "stream": "bokmaal",
            "level": "A1",
            "tags": ["drikk", "helse"],
        },
        {
            "term": "vatn",
            "translation": "water",
            "translation_en": "water",
            "translation_ru": "вода",
            "translation_nb": "vann",
            "explanation": "Vatn står på bordet. (Nynorsk)",
            "stream": "nynorsk",
            "level": "A1",
            "tags": ["drikk", "helse"],
        },
        {
            "term": "water",
            "translation": "вода",
            "translation_en": "water",
            "translation_ru": "вода",
            "translation_nb": "vann",
            "explanation": "I always bring a bottle of water. (English)",
            "stream": "english",
            "level": "A1",
            "tags": ["drink", "health"],
        },
        # morning
        {
            "term": "morgen",
            "translation": "morning",
            "translation_en": "morning",
            "translation_ru": "утро",
            "translation_nb": "morgen",
            "explanation": "Om morgenen drikk eg kaffi. (Bokmål)",
            "stream": "bokmaal",
            "level": "A1",
            "tags": ["tid", "hverdag"],
        },
        {
            "term": "morgon",
            "translation": "morning",
            "translation_en": "morning",
            "translation_ru": "утро",
            "translation_nb": "morgen",
            "explanation": "Kvar morgon vaknar vi tidleg. (Nynorsk)",
            "stream": "nynorsk",
            "level": "A1",
            "tags": ["tid", "kvardag"],
        },
        {
            "term": "morning",
            "translation": "утро",
            "translation_en": "morning",
            "translation_ru": "утро",
            "translation_nb": "morgen",
            "explanation": "The morning is quiet and cold. (English)",
            "stream": "english",
            "level": "A1",
            "tags": ["time", "daily"],
        },
        # evening
        {
            "term": "kveld",
            "translation": "evening",
            "translation_en": "evening",
            "translation_ru": "вечер",
            "translation_nb": "kveld",
            "explanation": "Vi ser ein film om kvelden. (Bokmål)",
            "stream": "bokmaal",
            "level": "A1",
            "tags": ["tid", "fritid"],
        },
        {
            "term": "kveld",
            "translation": "evening",
            "translation_en": "evening",
            "translation_ru": "вечер",
            "translation_nb": "kveld",
            "explanation": "Om kvelden les eg ei bok. (Nynorsk)",
            "stream": "nynorsk",
            "level": "A1",
            "tags": ["tid", "fritid"],
        },
        {
            "term": "evening",
            "translation": "вечер",
            "translation_en": "evening",
            "translation_ru": "вечер",
            "translation_nb": "kveld",
            "explanation": "In the evening we talk with friends. (English)",
            "stream": "english",
            "level": "A1",
            "tags": ["time", "free_time"],
        },
        # family
        {
            "term": "familie",
            "translation": "family",
            "translation_en": "family",
            "translation_ru": "семья",
            "translation_nb": "familie",
            "explanation": "Familien et middag saman. (Bokmål)",
            "stream": "bokmaal",
            "level": "A1",
            "tags": ["familie"],
        },
        {
            "term": "familie",
            "translation": "family",
            "translation_en": "family",
            "translation_ru": "семья",
            "translation_nb": "familie",
            "explanation": "Familien bur i ein liten by. (Nynorsk)",
            "stream": "nynorsk",
            "level": "A1",
            "tags": ["familie"],
        },
        {
            "term": "family",
            "translation": "семья",
            "translation_en": "family",
            "translation_ru": "семья",
            "translation_nb": "familie",
            "explanation": "My family lives in Norway now. (English)",
            "stream": "english",
            "level": "A1",
            "tags": ["family"],
        },
        # child
        {
            "term": "barn",
            "translation": "child",
            "translation_en": "child",
            "translation_ru": "ребёнок",
            "translation_nb": "barn",
            "explanation": "Barnet går i barnehage. (Bokmål)",
            "stream": "bokmaal",
            "level": "A1",
            "tags": ["familie", "skole"],
        },
        {
            "term": "barn",
            "translation": "child",
            "translation_en": "child",
            "translation_ru": "ребёнок",
            "translation_nb": "barn",
            "explanation": "Barn leikar ute i hagen. (Nynorsk)",
            "stream": "nynorsk",
            "level": "A1",
            "tags": ["familie", "skule"],
        },
        {
            "term": "child",
            "translation": "ребёнок",
            "translation_en": "child",
            "translation_ru": "ребёнок",
            "translation_nb": "barn",
            "explanation": "The child speaks both Norwegian and Russian. (English)",
            "stream": "english",
            "level": "A1",
            "tags": ["family", "school"],
        },
        # bus
        {
            "term": "buss",
            "translation": "bus",
            "translation_en": "bus",
            "translation_ru": "автобус",
            "translation_nb": "buss",
            "explanation": "Eg tek buss til jobben. (Bokmål)",
            "stream": "bokmaal",
            "level": "A1",
            "tags": ["reise"],
        },
        {
            "term": "buss",
            "translation": "bus",
            "translation_en": "bus",
            "translation_ru": "автобус",
            "translation_nb": "buss",
            "explanation": "Vi ventar på bussen. (Nynorsk)",
            "stream": "nynorsk",
            "level": "A1",
            "tags": ["reise"],
        },
        {
            "term": "bus",
            "translation": "автобус",
            "translation_en": "bus",
            "translation_ru": "автобус",
            "translation_nb": "buss",
            "explanation": "The bus is often full in the morning. (English)",
            "stream": "english",
            "level": "A1",
            "tags": ["travel"],
        },
        # shop
        {
            "term": "butikk",
            "translation": "shop",
            "translation_en": "shop",
            "translation_ru": "магазин",
            "translation_nb": "butikk",
            "explanation": "Butikken stenger klokka ni. (Bokmål)",
            "stream": "bokmaal",
            "level": "A1",
            "tags": ["handel"],
        },
        {
            "term": "butikk",
            "translation": "shop",
            "translation_en": "shop",
            "translation_ru": "магазин",
            "translation_nb": "butikk",
            "explanation": "Eg kjøper brød i butikken. (Nynorsk)",
            "stream": "nynorsk",
            "level": "A1",
            "tags": ["handel"],
        },
        {
            "term": "shop",
            "translation": "магазин",
            "translation_en": "shop",
            "translation_ru": "магазин",
            "translation_nb": "butikk",
            "explanation": "There is a small shop on the corner. (English)",
            "stream": "english",
            "level": "A1",
            "tags": ["shopping"],
        },
        # weather
        {
            "term": "vær",
            "translation": "weather",
            "translation_en": "weather",
            "translation_ru": "погода",
            "translation_nb": "vær",
            "explanation": "Været er kaldt i dag. (Bokmål)",
            "stream": "bokmaal",
            "level": "A1",
            "tags": ["vær"],
        },
        {
            "term": "vêr",
            "translation": "weather",
            "translation_en": "weather",
            "translation_ru": "погода",
            "translation_nb": "vær",
            "explanation": "Vêret er fint om sommaren. (Nynorsk)",
            "stream": "nynorsk",
            "level": "A1",
            "tags": ["vêr"],
        },
        {
            "term": "weather",
            "translation": "погода",
            "translation_en": "weather",
            "translation_ru": "погода",
            "translation_nb": "vær",
            "explanation": "The weather changes quickly in Norway. (English)",
            "stream": "english",
            "level": "A1",
            "tags": ["weather"],
        },
    ]

    for item in items:
        GlossaryTerm.objects.update_or_create(
            term=item["term"],
            stream=item["stream"],
            level=item["level"],
            defaults=item,
        )


def unreset_glossary_batch2(apps, schema_editor):
    GlossaryTerm = apps.get_model("exams", "GlossaryTerm")
    terms = [
        "kopp",
        "cup",
        "vann",
        "vatn",
        "water",
        "morgen",
        "morgon",
        "morning",
        "kveld",
        "evening",
        "familie",
        "family",
        "barn",
        "child",
        "buss",
        "bus",
        "butikk",
        "shop",
        "vær",
        "vêr",
        "weather",
    ]
    GlossaryTerm.objects.filter(term__in=terms).delete()


class Migration(migrations.Migration):
    dependencies = [
        ("exams", "0015_reset_glossary_sample"),
    ]

    operations = [
        migrations.RunPython(
            reset_glossary_batch2,
            reverse_code=unreset_glossary_batch2,
        ),
    ]
