# Generated by Django 5.2.8 on 2026-03-29 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("exams", "0029_userlexeme_indexes"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="userlexeme",
            new_name="exams_userl_user_id_5ff9d1_idx",
            old_name="exams_user_user_id_1293be_idx",
        ),
        migrations.RenameIndex(
            model_name="userlexeme",
            new_name="exams_userl_user_id_c18ed8_idx",
            old_name="exams_user_user_id_3c67bb_idx",
        ),
        migrations.RenameIndex(
            model_name="userlexeme",
            new_name="exams_userl_user_id_8dd2dc_idx",
            old_name="exams_user_user_id_gloss_idx",
        ),
        migrations.RenameIndex(
            model_name="userlexeme",
            new_name="exams_userl_user_id_a6fe8d_idx",
            old_name="exams_user_user_id_kind_idx",
        ),
        migrations.RenameIndex(
            model_name="userlexeme",
            new_name="exams_userl_user_id_a2787d_idx",
            old_name="exams_user_user_id_lang_idx",
        ),
    ]
